import {StyleSheet} from 'react-native';
import {scale} from '../../../Infrastructure/utils/screenUtility';
const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#ffff',
    paddingBottom: scale(10),
  },
  headerCard: {
    backgroundColor: '#F4F5F7',
    height: scale(72),
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: scale(10),
  },
  content: {
    paddingHorizontal: scale(5),
  },
  headerText: {
    fontSize: scale(14),
    color: '#4D4F5C',
    fontFamily: 'SourceSansPro-SemiBold',
  },
  headerLeft: {
    fontSize: scale(18),
    color: '#4D4F5C',
    fontFamily: 'SourceSansPro-Regular',
  },
  headerRight: {
    fontSize: scale(18),
    color: '#4D4F5C',
    fontFamily: 'SourceSansPro-SemiBold',
  },
  messageText: {
    fontSize: scale(16),
    color: '#4D4F5C',
    fontFamily: 'SourceSansPro-Regular',
    marginTop: scale(5),
    textAlign: 'justify',
    marginLeft: scale(5),
  },
  horizontalBar: {
    borderBottomColor: '#687C93',
    borderBottomWidth: 1,
    marginVertical: scale(10),
  },
  statusCount: {
    fontSize: scale(12),
    color: '#4D4F5C',
    fontFamily: 'SourceSansPro-Regular',
    marginLeft: scale(5),
  },
  actionView: {
    height: scale(42),
    backgroundColor: '#F4F5F7',
    marginTop: scale(10),
    flexDirection: 'row',
    alignItems: 'center',
  },
  footerText: {
    fontSize: scale(14),
    color: '#10A0DA',
    fontFamily: 'SourceSansPro-Regular',
    marginLeft: scale(5),
  },
  footerProfile: {
    backgroundColor: '#FFFFFF',
    height: scale(48),
    width: '100%',
    paddingHorizontal: scale(5),
    alignItems: 'center',
    flexDirection: 'row',
  },
  TextInput: {
    marginTop: scale(5),
    borderRadius: 4,
    borderColor: '#C3D0DE',
    borderWidth: 1,
    height: scale(40),
    fontSize: scale(14),
    fontFamily: 'SourceSansPro-Regular',
    paddingHorizontal: scale(10),
    color: '#4D4F5C',
    backgroundColor: '#fff',
    width: '80%',
    marginLeft: scale(5),
  },
  footerProfileText: {
    fontSize: scale(16),
    color: '#D5D5D5',
    fontFamily: 'SourceSansPro-SemiBold',
    paddingHorizontal: scale(5),
  },
  commentText: {
    fontSize: scale(18),
    color: '#4D4F5C',
    fontFamily: 'SourceSansPro-Regular',
  },
  profileName: {
    fontSize: scale(14),
    color: '#4D4F5C',
    fontFamily: 'SourceSansPro-SemiBold',
  },
  commentListText: {
    fontSize: scale(16),
    color: '#4D4F5C',
    fontFamily: 'SourceSansPro-Regular',
    marginTop: scale(5),
  },
  likeNreplyText: {
    fontSize: scale(14),
    color: '#687C93',
    fontFamily: 'SourceSansPro-SemiBold',
  },
  subCommentText: {
    fontSize: scale(14),
    color: '#4D4F5C',
    fontFamily: 'SourceSansPro-Regular',
  },
  subCommenterProfileText: {
    fontSize: scale(14),
    color: '#4D4F5C',
    fontFamily: 'SourceSansPro-SemiBold',
  },
  errorMessage: {
    fontSize: scale(10),
    fontFamily: 'SourceSansPro-Regular',
    color: 'red',
    marginLeft: scale(5),
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#00000040',
  },
  modalView: {
    // maxHeight: scale(500),
    // backgroundColor: 'pink',
    backgroundColor: 'white',
    borderRadius: scale(10),
    padding: scale(25),
    shadowColor: '#000',
    shadowOffset: {
      width: scale(0),
      height: scale(2),
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  radioTitle: {
    fontFamily: 'SourceSansPro-Regular',
    fontSize: scale(16),
    color: '#454545',
  },
  viewAnimated: {
    width: '100%',
  },
  viewContainer: {
    flex: 1,
    padding: 10,
    backgroundColor: '#E5E5E5',
    borderRadius: 20,
  },
});
export default styles;
